GET http://localhost:3001/expiry
###

POST http://localhost:3001/expiry
{
    EXPIRATION_ID: '0000003',
    PRODUCT_ID: 'test3',
    EXPIRY: '2023-02-01',
    LOT: 'test3lot',
    DISPOSITION: '',
    COMMENT: ''
}