GET http://localhost:3001/expiry
###

POST http://localhost:3001/expiry HTTP/1.1
content-type: application/json

{
    "expiration_id": "0000007",
    "product_id": "test7",
    "expiration_date": "2021-02-01",
    "lotno": "test7lot",
    "disposition": "",
    "comments": ""
}

###
GET http://localhost:3001/expiry/nextId
###

PUT http://localhost:3001/expiry/increment HTTP/1.1
content-type: application/json

{
    "nextId": "0000009"
}
###
